name: Build and Run Docker Containers

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hello-world .

  run-container-1:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Docker container 1
        run: docker run hello-world

  run-container-2:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Docker container 2
        run: docker run hello-world

  run-container-3:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Docker container 3
        run: docker run hello-world

  run-container-4:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Docker container 4
        run: docker run hello-world
